# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- azure-pipeline

pr: none

pool:
  vmImage: 'VS2017-Win2016'

variables:
  editorMotionControllerSolution: 'EditorMotionControllerDLL/EditorMotionController.sln'
  gpuStatsSolution: 'GpuStats/GpuStats.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(gpuStatsSolution)'
     
- task: VSBuild@1
  inputs:
    solution: '$(gpuStatsSolution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
